version: '3.7'

x-common-php: &common-php
  image: gsmainclusivetechlab/interop-test-platform:v1.1.4
  restart: always
  env_file: app.env
  depends_on:
    - mysqldb
    - redis
  security_opt:
    - apparmor:unconfined
  cap_add:
    - SYS_PTRACE
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - certbot_certs:/etc/nginx/ssl/letsencrypt
    - certbot_www:/var/www/certbot
    - storage:/var/www/html/storage/app

services:
  app:
    <<: *common-php
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      CONTAINER_ROLE: app

  queue:
    <<: *common-php
    environment:
      CONTAINER_ROLE: queue

  mysqldb:
    build:
      context: ./mysqldb
    restart: always
    env_file: mysql.env
    healthcheck:
      retries: 10
      test: [CMD, mysqladmin, ping, -h, localhost]
      timeout: 20s
    volumes:
      - mysqldata:/var/lib/mysql:rw

  redis:
    image: redis:5
    restart: always
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    volumes:
      - redisdata:/data:rw

  certbot:
    environment:
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped #+++
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint:
      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait
      $${!}; done;'"

  # mailhog:
  #   image: mailhog/mailhog
  #   restart: always
  #   ports:
  #     - '8086:8025'

  # phpmyadmin:
  #   depends_on:
  #     - mysqldb
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #     - PMA_HOST=mysqldb
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - /sessions

volumes:
  mysqldata: {}
  redisdata: {}
  ca_certs: {}
  certbot_certs: {}
  certbot_www: {}
  storage: {}
